CREATE DATABASE practice8;

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    login VARCHAR(16) UNIQUE NOT NULL
    );
    LOCK TABLES `teams` WRITE;

    INSERT INTO `teams` VALUES (1,'Petrov');

    UNLOCK TABLES;

CREATE TABLE IF NOT EXISTS teams (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(16) UNIQUE NOT NULL
    );
    LOCK TABLES `teams` WRITE;

    INSERT INTO `teams` VALUES (1,'teamA');

    UNLOCK TABLES;

CREATE TABLE IF NOT EXISTS users_teams (
    users_id INT PRIMARY KEY,
    teams_id INT PRIMARY KEY
    );

    LOCK TABLE users_teams WRITE;

    INSERT INTO users_teams VALUES (1, 1);

    UNLOCK TABLES;